# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.18.0'
  displayName: 'Install Node.js'


- script: |
    cd '$(System.DefaultWorkingDirectory)/telecom-angular'
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webApp'
    WebAppName: 'telecom-angular'
    packageForLinux: 'dist/telecom-angular'