# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.18.0'
  displayName: 'Install Node.js'


- script: |
    cd '$(System.DefaultWorkingDirectory)/telecom-angular'
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/$(Build.Configuration)/**/?(*.exe|*.dll|*.pbd)'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/telecom-angular/dist/telecom-angular'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'telecome-angular'
    publishLocation: 'Container'

- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'current'
    artifactName: 'telecom-angular'
    targetPath: '$(Pipeline.Workspace)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure subscription 1(bb022011-daf1-4a56-809e-e930ae46828a)'
    appType: 'webApp'
    WebAppName: 'telecom-angular'
    packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'